POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Pablo",
    "phone": "+593-0999-844118"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Adriana",
    "number": "+593-0989-768444"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jorge",
    "number": "+593-0954-213578"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "+593-0954-213578"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Jorge",
    "number": "+593-0985325481"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "lol",
    "number": "+593 0976481288"
}

### Testing number validations

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Adriana",
    "number": "12-135456"
}