PUT http://localhost:3001/api/persons/66a01d8a7fb0c5a66daf83e3
Content-Type: application/json

{
    "number":"025-8743197"
}

### Testing invalid id

PUT http://localhost:3001/api/persons/3433141414123121
Content-Type: application/json

{
    "name":"025-8743197"
}

### Testing name validation

PUT http://localhost:3001/api/persons/66a01d8a7fb0c5a66daf83e3
Content-Type: application/json

{
    "name":"lol"
}

### Testing number validation

PUT http://localhost:3001/api/persons/66a6f92de40acef8bcaf5982
Content-Type: application/json

{
    "number":"12-134552"
}